# Generated by Django 4.2.13 on 2024-07-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/dzlveh6fi/image/upload/v1718114697/bodypump2_yjclsk.jpg', max_length=500),
        ),
    ]
